[package]
name = "proxima_backend_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
proxima_backend = {path = ".."}
openai = "1.1.0"
openai-api-rs = "9.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.31"
reqwest-streams = "0.10.0"